### ISSUE TITLE
Add configurable openmw cfg location

### ISSUE THREAD

**Issue by zachary-cauchi** [glassmancody/waza_lightfixes#8]
The current implementation automatically resolves the `openmw.cfg` from the default OS-specific locations. This does not account for portable installations where the `openmw.cfg` file  is in a non-standard location.

An idea might be to add a new `openmw_cfg_path` to the `[General]` section in the cfg file to load up non-standard paths. By default, if empty or set to `?userdata?`, it follows the usual standard paths. If set to something else, attempt to load the cfg from that path.

**Comment by vazanoir** [comment]
It also doesn't resolves standard location of other ways of installing OpenMW, like the Flatpak version, which is at `$HOME/.var/app/org.openmw.OpenMW/config/openmw/openmw.cfg` on linux systems

**Comment by glassmancody** [comment]
This should be in now, thanks @zachary-cauchi  and @hristoast 

I'll upload binaries shortly
